on:
  workflow_call:
    inputs:
      AWS_DEPLOY_REGION:
        required: false
        type: string
        default: "eu-west-1"
      domain:
        required: true
        type: string
      team:
        required: true
        type: string
      dotnet-version:
        required: false
        type: string
        default: "6.0.x"
    secrets:
      AWS_CICD_ACCOUNT:
        required: true
      AWS_CICD_API_URL:
        required: true
      AWS_CICD_API_REGION:
        required: true

jobs:
  Account:
    uses: mathem-se/gh-account-mapping/.github/workflows/workflow.yml@main
    with:
      branch: ${{ github.ref_name }}
      role-session-name: "github-actions-oidc-session"
    secrets:
      AWS_ACCOUNT: ${{ secrets.AWS_CICD_ACCOUNT }}
      AWS_API: ${{ secrets.AWS_CICD_API_URL }}
      AWS_REGION: ${{ secrets.AWS_CICD_API_REGION }}

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Run tests
        uses: ./.github/actions/build
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

  Release:
    needs: [Account, Test]
    uses: ./.github/workflows/step-release-aws.yml
    with:
      domain: ${{ inputs.domain }}
      team: ${{ inputs.team }}
      environment: ${{ needs.Account.outputs.environment }}
      AWS_DEPLOY_REGION: ${{ inputs.AWS_DEPLOY_REGION }}
      dotnet-version: ${{ inputs.dotnet-version }}
    secrets:
      AWS_CICD_API_REGION: ${{ secrets.AWS_CICD_API_REGION }}
      AWS_ACCOUNT: ${{ needs.Account.outputs.account }}
