on:
  workflow_call:
    inputs:
      dotnet-version:
        required: false
        type: string
        default: "6.0.x"
      private-nuget-source:
        required: false
        type: boolean
        default: false
      private-nuget-username:
        required: false
        type: string
    secrets:
      GH-TOKEN:
        required: false

jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      
      - name: Add private nuget source
        if: ${{ inputs.private-nuget-source }}
        run: dotnet nuget add source "https://nuget.pkg.github.com/mathem-se/index.json" --name "mathem-se" --username "${{ inputs.private-nuget-username }}" --password " ${{ secrets.GH-TOKEN }}" --store-password-in-clear-text
      
      - name: Verify code formating 
        run: dotnet format --verify-no-changes
