on:
  workflow_call:
    inputs:
      dotnet-version:
        required: false
        type: string
        default: "6.0.x"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Run tests
        uses: ./.github/actions/build
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
